# Generated by Django 4.0.4 on 2022-05-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Цена курса')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('vote_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('Up', 'good'), ('Down', 'bad')], default='good', max_length=255)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Ваш комментарий')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='courses.course')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='users.customer')),
            ],
        ),
    ]
